# Generated by Django 5.0.4 on 2024-04-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_delete_admin_delete_superadmin_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='name',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='ban',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
