# Generated by Django 5.0.4 on 2024-05-21 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_article_time_alter_comment_time_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='default.jpg', upload_to='img/')),
                ('stateCode', models.CharField(default='0', max_length=1)),
                ('name', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=11)),
                ('time', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('user', '普通用户'), ('admin', '管理员'), ('root', '超级管理员')], default='user', max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default='2024-05-21 12:19:11', verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default='2024-05-21 12:19:11', verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user1', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user1', verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user1', verbose_name='用户'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
