# Generated by Django 5.0.4 on 2024-05-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_user1_alter_article_time_alter_comment_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default='2024-05-24 12:11:36', verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default='2024-05-24 12:11:36', verbose_name='评论时间'),
        ),
    ]
