# Generated by Django 5.0.4 on 2024-04-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_ban_name_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=12),
        ),
    ]
