# Generated by Django 5.0.4 on 2024-04-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
