# Generated by Django 5.0.4 on 2024-04-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='img'),
        ),
    ]
